name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run make
      run: make deploy
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4